### ISSUE TITLE
Unable to fill order completely.

### ISSUE THREAD

**Issue by walker007** [victorratts13/RTbos#1]
Tenho adicionado LTC  em minha carteira do POLONIEX, o Bot executa os 5 minutos iniciais, quando ele vai comprar retorna esse JSON {"error":"Unable to fill order completely."}. Logo em seguida fala que está aguardando próxima ordem, isso é algum problema, ou pode continuar executando o código?

**Comment by victorratts13** [comment]
boa tarde,
inicialmente vc precisa ter saldo em BTC, esse erro ocorre por não
conseguir completar a ordem de compra/venda

Em sex, 22 de mar de 2019 às 16:05, walker007 <notifications@github.com>
escreveu:

**Comment by walker007** [comment]
É possível alterar a moeda para completar a ordem?

**Comment by victorratts13** [comment]
sim, vc deve ir em PAR= (par da moeda que quer)
ou vc pode ir direto na linha 110 onde vc pode configurar diretamente os
pares



Em sex, 22 de mar de 2019 às 16:25, walker007 <notifications@github.com>
escreveu:

**Comment by victorratts13** [comment]
![IDE_RTbos](https://i.imgur.com/aw6htWq.png)

**Comment by victorratts13** [comment]
aqui está detalhado, caso haja alguma duvida:
![RTbos_IDE-02](https://i.imgur.com/43XD93Q.gif)
